# Generated by Django 5.0.1 on 2024-01-07 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='attendees',
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rsvp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvp.rsvp')),
            ],
        ),
    ]
