# Generated by Django 5.0.1 on 2024-01-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_rsvp_party_total_alter_attendee_rsvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='email',
            field=models.EmailField(default='', max_length=200),
        ),
    ]
