# Generated by Django 5.0.1 on 2024-03-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0005_remove_rsvp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='is_attending',
            field=models.BooleanField(default=True),
        ),
    ]
